site_name: NOTES
site_author: sakuratsuyu
site_url: 'https://sakuratsuyu.github.io/Note'

repo_name: 'sakuratsuyu/Note'
repo_url: 'https://github.com/sakuratsuyu/Note'

theme:
  name: material
  custom_dir: overrides
  language: zh
  direction: ltr
  icon:
    logo: material/taco
    repo: fontawesome/brands/github-alt
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-variant-outline
        name: dark mode
      primary: white
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-variant
        name: light mode
      primary: dark
      accent: deep orange
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

copyright: Copyright &copy; 2022 sakuratsuyu

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/sakuratsuyu
      name: Github
    - icon: fontawesome/regular/envelope
      link: mailto:sakuratsuyu@outlook.com
  generator: true

extra_css:
  - css/basic.css
  - css/admonition.css
  - css/flink.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.css

extra_javascript:
# Katex Configuration
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.js

# Mathjax Configuration
#  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#  - js/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: custom
      custom_format: "%Y.%m.%d %H:%M:%S %Z"
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - comming_soon.md
        - discussion.md
#  - git-authors:
#      exclude:
#          - index.md
#          - discussion.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Content
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta

nav:
  - Home Page:
    - index.md
    - Plan: tasklist.md
    - Blogroll: discussion.md
  - Mathematics Basis:
    - Mathematics_Basis/index.md
    - 离散数学 | Discrete Mathematics:
      - Chap 1 | Logic and Proofs : Mathematics_Basis/DM/Chap_1.md
      - Chap 2 | Sets and Functions: Mathematics_Basis/DM/Chap_2.md
      - Chap 3 | Algorithms: Mathematics_Basis/DM/Chap_3.md
      - Chap 4 | Number Theory: Mathematics_Basis/DM/Chap_4.md
      - Chap 5 | Induction and Recursion: Mathematics_Basis/DM/Chap_5.md
      - Chap 6 | Counting : Mathematics_Basis/DM/Chap_6.md
      - Chap 7 | Discrete Probability: Mathematics_Basis/DM/Chap_7.md
      - Chap 8 | Advanced Counting: Mathematics_Basis/DM/Chap_8.md
      - Chap 9 | Relations: Mathematics_Basis/DM/Chap_9.md
      - Chap 10 | Graphs : Mathematics_Basis/DM/Chap_10.md
      - Chap 11 | Trees : Mathematics_Basis/DM/Chap_11.md
      - Chap 12 & 13 | Boolean Algrebra & Modeling Computation: Mathematics_Basis/DM/Chap_12_13.md
    - 概率论与数理统计 | Probability and Statistics: Mathematics_Basis/PS/Review.md
    - 数值分析 | Numerical Analysis:
      - Class Notes : Mathematics_Basis/NA/class_notes.md
      - Chap 1 | Math Prelims: Mathematics_Basis/NA/Chap_1.md
      - Chap 2 | Solve Equation: Mathematics_Basis/NA/Chap_2.md
      - Chap 3 | Interpolation : Mathematics_Basis/NA/Chap_3.md
      - Chap 4 | Differentiation and Integration: Mathematics_Basis/NA/Chap_4.md
      - Chap 5 | IVP for ODE : Mathematics_Basis/NA/Chap_5.md
      - Chap 6 | Solve Linear System Directly: Mathematics_Basis/NA/Chap_6.md
      - Chap 7 | Solve Linear System Iteratively: Mathematics_Basis/NA/Chap_7.md
      - Chap 8 | Approximation: Mathematics_Basis/NA/Chap_8.md
      - Chap 9 | Eigenvalues : Mathematics_Basis/NA/Chap_9.md
  - Computer Science Courses:
    - Computer_Science_Courses/index.md
    - The Missing Semester of Your CS Education: Computer_Science_Courses/MISSING/note.md
    - 数据结构基础 | Fundemental of Data Structure:
      - Class Notes : Computer_Science_Courses/FDS/class_notes.md
      - Algorithm Analysis: Computer_Science_Courses/FDS/Algorithm_Analysis.md
      - Lists, Stacks and Queues: Computer_Science_Courses/FDS/Lists_Stacks_and_Queues.md
      - Trees: Computer_Science_Courses/FDS/Trees.md
      - Hashing: Computer_Science_Courses/FDS/Hashing.md
      - Priority Queues: Computer_Science_Courses/FDS/Priority_Queues.md
      - Sort: Computer_Science_Courses/FDS/Sort.md
      - Disjoint Set: Computer_Science_Courses/FDS/Disjoint_Set.md
      - Graph: Computer_Science_Courses/FDS/Graph.md
    - 计算机视觉导论 | Introduction to Computer Vision:
      - Lecture 1 : Computer_Science_Courses/ICV/1_Introduction.md
      - Lecture 2 : Computer_Science_Courses/ICV/2_Image_Formation.md
      - Lecture 3 : Computer_Science_Courses/ICV/3_Image_Processing.md
      - Lecture 4 : Computer_Science_Courses/ICV/4_Model_Fitting_and_Optimization.md
      - Lecture 5 : Computer_Science_Courses/ICV/5_Image_Matching_and_Motion_Estimation.md
      - Lecture 6 : Computer_Science_Courses/ICV/6_Image_Stitching.md
      - Lecture 7 : Computer_Science_Courses/ICV/7_Structure_from_Motion.md
      - Lecture 8 : Computer_Science_Courses/ICV/8_Depth_Estimation_and_3D_Reconstruction.md
      - Lecture 9 : Computer_Science_Courses/ICV/9_Deep_Learning.md
      - Lecture 10 : Computer_Science_Courses/ICV/10_Recognition.md
      - Lecture 11 : Computer_Science_Courses/ICV/11_3D_Deep_Learning.md
      - Lecture 12/13 : Computer_Science_Courses/ICV/12_13_Computational_Photography.md
  - Tools:
    - comming_soon.md
  - Pot-pourri:
    - comming_soon.md
